#!/bin/sh
set -e

if [ -z "$CIEL_DB_APP_PASSWORD" ]; then
  echo "CIEL_DB_APP_PASSWORD is empty; refusing to create the ciel_app role." >&2
  exit 1
fi

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<SQL
CREATE ROLE ciel_app LOGIN PASSWORD '$CIEL_DB_APP_PASSWORD';
REVOKE ALL ON DATABASE $POSTGRES_DB FROM PUBLIC;
GRANT CONNECT ON DATABASE $POSTGRES_DB TO ciel_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ciel_app;
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ciel_app;
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ciel_app;
SQL
